#!/usr/bin/env bash
#Bash script that will display information about subdomains

function get_record_info {
  local domain=$1
  local subdomain=$2
  local record_info=$(dig +short $subdomain.$domain | awk '{print $1}')
  local record_type=$(dig $subdomain.$domain | awk '/ANSWER SECTION/{getline; print $2}')
  echo "The subdomain $subdomain is a $record_type record and points to $record_info"
}

if [ $# -eq 0 ]; then
  echo "Error: domain parameter is required"
  exit 1
fi

domain=$1
if [ $# -eq 1 ]; then
  get_record_info $domain www
  get_record_info $domain lb-01
  get_record_info $domain web-01
  get_record_info $domain web-02
else
  subdomain=$2
  get_record_info $domain $subdomain
fi
