#!/usr/bin/env bash


# Update package list
sudo apt-get update

# Install HAproxy
sudo apt-get install --no-install-recommends software-properties-common
sudo apt-get install haproxy=2.6.\*
sudo apt-get -y install haproxy

# Edit configuration file
server_config=\
"
frontend http-in
   bind *:80
   mode http
   default_backend servers

backend servers
   mode http
   balance roundrobin
   server 169278-web-01 54.227.128.48:80 check
   server 169278-web-02 100.25.119.208:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
